### ISSUE TITLE
fragment column readCount

### ISSUE THREAD

**Issue by gewoods** [HYsxe/PRINT#18]
Hi, 

I noticed that the function computeCountTensor does not consider column 5 readCount in the fragments file, which is been viewed as extra columns. Is there a way to fix it if I have bulk data? 

Best, 
Lyn

**Comment by HYsxe** [comment]
Hi!

Thanks for this question! Yes we do not consider column 5 by design because if you have multiple fragments with the exact same start and end they are very likely PCR duplicates. In a simplified model, imagine you have a region of 1kb, and Tn5 can cut any position, then the probability of two fragments to have the exact same start and end would be 1 / (1000 choose 2) which is roughly 1 in half a million reads. Usually we only get at most a few thousand reads per cCRE, so this is very unlikely by chance. Of course in reality the uneven accessibility and the presence of Tn5 bias will reduce the number of all likely combinations, but still we found it more appropriate to treat them as PCR duplicates rather than count the 5th column.

However, if you have extremely deep bulk data, or in vitro experiments where sequencing depth is super high, you might start getting bona fide different reads starting and ending at the same place, but in this case I believe it is difficult to tell them apart with PCR duplicates unless you have UMIs.

Yan
