### ISSUE TITLE
Loading back in chunked RDS data

### ISSUE THREAD

**Issue by maxdudek** [HYsxe/PRINT#9]
Hi,

After running `getCountTensor()` and `getFootprints()`, the results are (presumably) saved in `chunkedCountTensor` and `chunkedFootprintResults`. After restarting R, I now want to run `getTFBS()`, but I would prefer not to rerun the previous two commands since they take some time. How can I load the chunked rds data into my R project so I don't have to recalculate them? Couldn't find anything about it in the tutorial.

Thanks!
Max

**Comment by maxdudek** [comment]
Oops, nevermind - I missed the bit of code that automatically loads in the rds if it already exists.

**Comment by HYsxe** [comment]
Glad you found it! In general getTFBS() doesn't require you to run getFootprints() first because getTFBS() will internally compute footprints for the required scales and use them to score TF binding. You can think of these two as parallel functionalities. In addition, if you take a look at our latest updated tutorial, I show an example of how to use getTFBindingSE() to load the TF binding scores of all candidate sites and pseudo-bulks into a combined SummarizedExperiment object. I hope this is helpful!
